sensu:
  build: ./sensu
  restart: always
  volumes: 
    - "./etc/sensu:/etc/sensu"
  environment:
    RABBITMQ_HOST: rabbitmq
    REDIS_HOST: redis
  ports:
    - "3000:3000"
    - "4567:4567"
  links:
    - rabbitmq
    - redis

cpuagent:
  build: ./cpu-agent
  restart: always
  volumes:
    - "./etc/cpu-agent:/etc/sensu"
  links:
    - rabbitmq

httpagent:
  build: ./http-agent
  restart: always
  environment:
    - URL=http://deviceregistry.iot.dev.cantireinnovations.com/
    - BEARER_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiJ0ZXN0IiwiaWF0IjoxNDQ0MTUzOTkwLCJhdWQiOiJjdGkuaW90IiwiaXNzIjoiY3RpLm9hdXRoIn0.u8xX8FqYlj4BDwZUt3n6s6lH_yorxAtyoMRuN4igq6o
  volumes:
    - "./etc/http-agent:/etc/sensu"
  links:
    - rabbitmq

standalone:
  build: ./http-agent
  restart: always
  environment:
    - URL=http://deviceregistry.iot.dev.cantireinnovations.com/
    - BEARER_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiJ0ZXN0IiwiaWF0IjoxNDQ0MTUzOTkwLCJhdWQiOiJjdGkuaW90IiwiaXNzIjoiY3RpLm9hdXRoIn0.u8xX8FqYlj4BDwZUt3n6s6lH_yorxAtyoMRuN4igq6o
  volumes:
    - "./etc/standalone-http-agent:/etc/sensu"
  links:
    - rabbitmq

rabbitmqagent:
  build: ./rabbit-agent
  restart: always
  volumes: 
    - "./etc/rabbit-agent:/etc/sensu"
  links:
    - rabbitmq

rabbitmq:
  hostname: rabbitmq
  image: rabbitmq:3.4.4-management
  restart: always
  volumes:
    - "./etc/rabbitmq:/etc/rabbitmq"
    - "./local/rabbit:/data"
  ports:
    - "5672:5672"
    - "5671:5671"
    - "15672:15672"
    - "15671:15671"

redis:
  image: redis:2.8.19
  restart: always
  ports:
    - "6379:6379"

sensuhttpcheck:
  image: sensu-http-check
  restart: always
  environment:
    - CLIENT_NAME=sensu-http-check
    - RABBITMQ_HOST=rabbitmq
    - RABBITMQ_PORT=5671
    - RABBITMQ_VHOST=/
    - RABBITMQ_USER=guest
    - RABBITMQ_PASS=guest
    - URL=http://deviceregistry.iot.dev.cantireinnovations.com/
  volumes:
    - "./etc/standalone-http-agent/ssl/:/etc/sensu/ssl/"
  links:
    - rabbitmq